## SpoutBonus - Give players a daily bonus for using Spoutcraft
#
# enable more verbose logging to console
debug: false
#
# economy bonus
economy-bonus: false
economy-amount: 1
#
# item bonus
item-bonus: true
item-amount: 1
item-type: 264
