name: SpoutBonus
main: com.moosemanstudios.SpoutBonus.SpoutBonusBukkit
author: moose517
description: Daily reward for using spoutcraft client
version: ${version}
website: http://moosemanstudios.com/programming
commands:
    spoutbonus:
        description: All SpoutBonus commands
permissions:
    spoutbonus.admin:
        description: All SpoutBonus admin related permissions
        
